---
title: "Surface Area Calculations from Wax Dipping"
author: "HM Putnam, AS Huffmyer; edited ZD 9/19/2026"
date: "10/26/2021"
output:
  github_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

## install packages if you dont already have them
if (!require("tidyverse")) install.packages("tidyverse")

# load packages
library(tidyverse)
```

```{r}
#load wax data
smpls <- read.csv("../../data_phys/wax_dipped.csv", header=TRUE)
stnds <- read.csv("../../data_phys/wax_standards.csv", header=TRUE)

smpls$species <- substr(smpls$fragment, 1, 3)

smpls$delta.mass.g <- smpls$Skeleton.Wax.Dipped.Weight-smpls$Skeleton.Dry.Weight
stnds$delta.mass.g <- stnds$Wax.Dipped.Weight-stnds$Dry.Weight

#calculate the surface area of the cylindrical standards from the diameter and length
# NOTE: the wax on the ends of the cylinder was scraped off, so they are not included in the surface area
stnds$rad <- stnds$Diameter_cm/2
stnds$surface.area.cm2 <- 2*pi*(stnds$rad)*(stnds$Length_cm)

# calculate the curve coefficients for slope and intercept to apply as the standard
stnd.curve <- lm(surface.area.cm2~delta.mass.g, data=stnds)
plot(surface.area.cm2~delta.mass.g, data=stnds)
stnd.curve$coefficients
summary(stnd.curve)$r.squared

#Calculate surface area using the standard curve
smpls$surface.area.cm2 <- stnd.curve$coefficients[2] * smpls$delta.mass.g + stnd.curve$coefficients[1]

#check the range to make sure your samples fall within the range of the standards
range(smpls$surface.area.cm2)
range(stnds$surface.area.cm2)

#Save the output for use in normilzation for phys assays
smpls%>%
  select(species, fragment, surface.area.cm2, Homogenate.Volume)%>%
  write_csv("../../output_phys/surface_area.csv")
```

### Below is not from Hollie + Ariana's code, but my own checks for outliers

```{r}
sum(smpls$surface.area.cm2 < min(stnds$surface.area.cm2) )
  # 29/126 samples had a surface area smaller than that of the smallest standard...

ggplot(smpls, aes(x = species, y = surface.area.cm2)) +
  geom_boxplot(outlier.color = "red", outlier.shape = 8, outlier.size = 3) +
  geom_jitter(width = 0.2, alpha = 0.5) +
  theme_bw() +
  labs(title = "Surface Area by Species with Outliers Highlighted",
       x = "Species",
       y = "Surface Area (cm²)")

ggplot(smpls, aes(x = surface.area.cm2)) +
  geom_histogram(bins=100) +
  facet_grid(species~.) + 
  theme_bw() +
  labs(title = "Surface Area by Species with Outliers Highlighted",
       x = "Species",
       y = "Surface Area (cm²)")
```

On 9/21/26, I checked the following outliers in the original data and re-scraped any cut surfaces that could've artifically inflated the wax-dipped weight. New weights are written next to the originals on the datasheet and trackable through github commit 9/21/26.

- MON_P24_C1
- POR_P3_C2
- POR_P3_H1
- POC_P12_C2

